version: '3'

services:
  app_blue:
    image: yimikaade/wonderful:devops-stage-two
    container_name: app_blue
    ports:
      - "8081:3000"

  app_green:
    image: yimikaade/wonderful:devops-stage-two
    container_name: app_green
    ports:
      - "8082:3000"

  nginx:
    image: nginx:1.29-alpine
    container_name: nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app_blue
      - app_green
